### PR TITLE
Update BUILD_15KHZ_BATOCERA.sh

### PR DESCRIPTION
**Pull request by yavimaya**
Lines starting from es.customsargs were appended to conf on each script launch.

### CODE REVIEW

**Comment by Redemp** [comment]
From ZFEBHVUE:

This is a Bash script that is designed to modify a configuration file called batocera.conf based on the contents of a backup file called batocera.conf.bak. The script first tries to locate a specific section in the batocera.conf.bak file by searching for a specific comment (## ES Settings, See wiki page on how to center EmulationStation) and determining the line number where this comment appears.

If the comment is found, the script then uses the sed command to extract all the lines in the batocera.conf.bak file that come before the section with the comment, up to the line just before the comment. This extracted content is then written to the batocera.conf file, effectively replacing its contents with the contents of the backup file up to the section with the comment.

If the comment is not found, the script assumes that the batocera.conf file has not been modified before, and simply copies the entire contents of the batocera.conf.bak file to the batocera.conf file.

By using this script, the contents of the batocera.conf file are updated only when necessary, and the original file is not appended with unnecessary data on each script launch.

**Comment by yavimaya** [comment]
That's the exact description of the code intent.
I realized because I used special ES Settings to center it. After launching the script twice, I saw that the es.customargs used to center ES and other configuration lines were duplicated at the end of batocera.conf. That made ES not to work as it should.
This part of code checks if this can happen and avoid it the way you detailed.

**Comment by yavimaya** [comment]
Last commit was to allow changing dotclock_min for main monitor and also if another monitor has been cosen for M.A.M.E.

**Comment by Redemp** [comment]
Closing PR and waiting for two seperate PR's instead. 
Just makes it easier for everyone to see what has been changed or added. 

Not only for the devs but also for the end user.

**Pull request closed without merging**
